name: 'Hello'
description: 'Says Hello'
inputs:
  who-to-greet:
    description: 'Who are we greeting'
    required: true
    default: 'World'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
